### ISSUE TITLE
Issue regarding the code simulation

### ISSUE THREAD

**Issue by fyouly** [Zhuzzq/EdgeFed-MARL-MEC#1]
Hi,
I recently read your paper <Federated Multi-Agent Actor-Critic Learning for Age Sensitive Mobile Edge Computing* [J]. IEEE Internet of Things Journal, 2021> and am interested about your model. I have tried to simulate your code but have following questions:
1. Do I need to first use 'pip -install -e' command to set up the MEC_env environment before simulate other python files?
2. When I tried to run the *_run.py files, it reports 'ImportError: cannot import name 'Space' from 'gym.spaces' error, so which version of gym did you use when simulating your code? 

Thank you very much for your time if you can answer my quries.

**Comment by Zhuzzq** [comment]
> 
1. It's not necessary if the paths are set correctly.
2. The version of gym is 0.17.2.

Thanks for your interests and hope it's helpful to you.

**Comment by fyouly** [comment]
> > 
> 
> 1. It's not necessary if the paths are set correctly.
> 2. The version of gym is 0.17.2.
> 
> Thanks for your interests and hope it's helpful to you.

It runs successfully with the gym version==0.17.2. Thanks for your timely reply!
